name: Deploy Worker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
            version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: pnpm install --frozen-lockfile
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  deploy-development:
    name: Deploy Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
            version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: pnpm install --frozen-lockfile
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: dev